<TileCard>:
    orientation: "vertical"
    size_hint: None, None
    size: dp(150), dp(150)
    padding: dp(12)
    spacing: dp(6)

    canvas.before:
        Color:
            rgba: root.bg_rgba
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [18, 18, 18, 18]

    Widget:
        size_hint_y: 0.12

    MDIcon:
        icon: root.icon_text
        halign: "center"
        theme_text_color: "Custom"
        text_color: 0, 0, 0, 1
        font_size: "42sp"
        size_hint_y: None
        height: dp(48)

    MDLabel:
        text: root.title
        halign: "center"
        valign: "middle"
        bold: True
        font_style: "Subtitle1"
        theme_text_color: "Custom"
        text_color: 0, 0, 0, 1
        size_hint_y: None
        height: dp(45)

    Widget:
        size_hint_y: 0.12
<BottomNav@MDBoxLayout>:
    size_hint_y: None
    height: dp(64)
    md_bg_color: 0.95, 0.95, 0.95, 1
    padding: dp(6)
    spacing: dp(4)

    MDIconButton:
        icon: "navigation-variant-outline"
        on_release: app.go_to("navigation")

    MDIconButton:
        icon: "chat-outline"
        on_release: app.go_to("chat")

    MDIconButton:
        icon: "bell-outline"
        on_release: app.go_to("reminder")

    MDIconButton:
        icon: "bluetooth"
        on_release: app.go_to("pairing")

    MDIconButton:
        icon: "vector-square"
        on_release: app.go_to("org")        