#:import dp kivy.metrics.dp


<TileCard>:
    orientation: "vertical"
    size_hint: None, None
    size: dp(150), dp(150)
    padding: dp(12)
    spacing: dp(6)

    canvas.before:
        Color:
            rgba: root.bg_rgba

        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius:
                [
                dp(18),
                dp(18),
                dp(18),
                dp(18)
                ]

    Widget:
        size_hint_y: 0.12

    MDIcon:
        icon: root.icon_text
        halign: "center"
        theme_text_color: "Custom"
        text_color: 0, 0, 0, 1
        font_size: "42sp"
        size_hint_y: None
        height: dp(48)

    MDLabel:
        text: root.title
        halign: "center"
        valign: "middle"
        bold: True
        font_style: "Subtitle1"
        theme_text_color: "Custom"
        text_color: 0, 0, 0, 1
        text_size: self.width, None
        size_hint_y: None
        height: dp(45)

    Widget:
        size_hint_y: 0.12


<BottomNav@MDBoxLayout>:
    size_hint_y: None
    height: dp(64)
    md_bg_color: 0.95, 0.95, 0.95, 1
    padding: dp(6)
    spacing: dp(4)

    MDIconButton:
        icon: "navigation-variant-outline"
        pos_hint: {"center_y": 0.5}
        on_release: app.go_to("navigation")

    MDIconButton:
        icon: "chat-outline"
        pos_hint: {"center_y": 0.5}
        on_release: app.go_to("chat")

    MDIconButton:
        icon: "bell-outline"
        pos_hint: {"center_y": 0.5}
        on_release: app.go_to("reminder")

    MDIconButton:
        icon: "note-multiple-outline"
        pos_hint: {"center_y": 0.5}
        on_release: app.go_to("tasks")

    MDIconButton:
        icon: "vector-square"
        pos_hint: {"center_y": 0.5}
        on_release: app.go_to("org")