ScreenManager:
    SplashScreen:
        name: "splash"
    CreateAccountScreen:
        name: "create_account"
    SignInScreen:
        name: "signin"
    DesiredHomeScreen:
        name: "home"
    ChatScreen:
        name: "chat"
    ReminderScreen:
        name: "reminder"
    TaskScreen:
        name: "tasks"
    NoteEditorScreen:
        name: "note_editor"
    OrgScreen:
        name: "organisation"
    SettingsScreen:
        name: "settings"
    NavigationScreen:
        name: "navigation"