<NavigationScreen>:
    name: "navigation"
    MDBoxLayout:
        orientation: "vertical"
        MDTopAppBar:
            title: "Navigation"
            left_action_items: [["arrow-left", lambda x: app.back_to_home()]]
        MDLabel:
            text: "Navigation page"
            halign: "center"


<ChatScreen>:
    name: "chat"
    MDBoxLayout:
        orientation: "vertical"
        MDTopAppBar:
            title: "Chat"
            left_action_items: [["arrow-left", lambda x: app.back_to_home()]]
        MDLabel:
            text: "Chat page"
            halign: "center"


<ReminderScreen>:
    name: "reminder"
    MDBoxLayout:
        orientation: "vertical"
        MDTopAppBar:
            title: "Reminder"
            left_action_items: [["arrow-left", lambda x: app.back_to_home()]]
        MDLabel:
            text: "Reminder page"
            halign: "center"


<PairingScreen>:
    name: "pairing"
    MDBoxLayout:
        orientation: "vertical"
        MDTopAppBar:
            title: "Device Pairing"
            left_action_items: [["arrow-left", lambda x: app.back_to_home()]]
        MDLabel:
            text: "Pairing page"
            halign: "center"


<OrgScreen>:
    name: "org"
    MDBoxLayout:
        orientation: "vertical"
        MDTopAppBar:
            title: "Connect to Organization"
            left_action_items: [["arrow-left", lambda x: app.back_to_home()]]
        MDLabel:
            text: "Organization page"
            halign: "center"


<SettingsScreen>:
    name: "settings"
    MDBoxLayout:
        orientation: "vertical"
        MDTopAppBar:
            title: "Settings"
            left_action_items: [["arrow-left", lambda x: app.back_to_home()]]
        MDLabel:
            text: "Settings page"
            halign: "center"
